# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Timezone
timezone: 'America/New_York'

# Files to exclude
exclude:
  - .envrc
  - CNAME
  - Gemfile
  - Gemfile.lock
  - bin
  - images

# Jekyll Plugins
plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji

# Permalink settings
permalink: ':year-:month-:day-:title.html'

# jekyll-readme-index config
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false

# jekyll-titltes-from-headings config
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

# Layout
theme: jekyll-theme-primer
title: How Do?

# Metadata
author:
  email: jpriddle@me.com
  github: itspriddle
  linkedin: itspriddle
  location: Clifton Park, NY
